/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: 'rgb(var(--md-primary) / <alpha-value>)',
        'on-primary': 'rgb(var(--md-on-primary) / <alpha-value>)',
        'primary-container': 'rgb(var(--md-primary-container) / <alpha-value>)',
        'on-primary-container': 'rgb(var(--md-on-primary-container) / <alpha-value>)',
        secondary: 'rgb(var(--md-secondary) / <alpha-value>)',
        'on-secondary': 'rgb(var(--md-on-secondary) / <alpha-value>)',
        'secondary-container': 'rgb(var(--md-secondary-container) / <alpha-value>)',
        'on-secondary-container': 'rgb(var(--md-on-secondary-container) / <alpha-value>)',
        tertiary: 'rgb(var(--md-tertiary) / <alpha-value>)',
        'on-tertiary': 'rgb(var(--md-on-tertiary) / <alpha-value>)',
        'tertiary-container': 'rgb(var(--md-tertiary-container) / <alpha-value>)',
        'on-tertiary-container': 'rgb(var(--md-on-tertiary-container) / <alpha-value>)',
        error: 'rgb(var(--md-error) / <alpha-value>)',
        'on-error': 'rgb(var(--md-on-error) / <alpha-value>)',
        'error-container': 'rgb(var(--md-error-container) / <alpha-value>)',
        'on-error-container': 'rgb(var(--md-on-error-container) / <alpha-value>)',
        background: 'rgb(var(--md-background) / <alpha-value>)',
        'on-background': 'rgb(var(--md-on-background) / <alpha-value>)',
        surface: 'rgb(var(--md-surface) / <alpha-value>)',
        'on-surface': 'rgb(var(--md-on-surface) / <alpha-value>)',
        'surface-variant': 'rgb(var(--md-surface-variant) / <alpha-value>)',
        'on-surface-variant': 'rgb(var(--md-on-surface-variant) / <alpha-value>)',
        'surface-dim': 'rgb(var(--md-surface-dim) / <alpha-value>)',
        'surface-bright': 'rgb(var(--md-surface-bright) / <alpha-value>)',
        'surface-container-lowest': 'rgb(var(--md-surface-container-lowest) / <alpha-value>)',
        'surface-container-low': 'rgb(var(--md-surface-container-low) / <alpha-value>)',
        'surface-container': 'rgb(var(--md-surface-container) / <alpha-value>)',
        'surface-container-high': 'rgb(var(--md-surface-container-high) / <alpha-value>)',
        'surface-container-highest': 'rgb(var(--md-surface-container-highest) / <alpha-value>)',
        outline: 'rgb(var(--md-outline) / <alpha-value>)',
        'outline-variant': 'rgb(var(--md-outline-variant) / <alpha-value>)',
        'inverse-surface': 'rgb(var(--md-inverse-surface) / <alpha-value>)',
        'inverse-on-surface': 'rgb(var(--md-inverse-on-surface) / <alpha-value>)',
        'inverse-primary': 'rgb(var(--md-inverse-primary) / <alpha-value>)',
        scrim: 'rgb(var(--md-scrim) / <alpha-value>)',
      },
      fontFamily: {
        sans: ['"M PLUS Rounded 1c"', 'system-ui', '-apple-system', 'sans-serif'],
      },
      fontSize: {
        'display-large': ['57px', { lineHeight: '64px', letterSpacing: '-0.25px' }],
        'display-medium': ['45px', { lineHeight: '52px', letterSpacing: '0px' }],
        'display-small': ['36px', { lineHeight: '44px', letterSpacing: '0px' }],
        'headline-large': ['32px', { lineHeight: '40px', letterSpacing: '0px' }],
        'headline-medium': ['28px', { lineHeight: '36px', letterSpacing: '0px' }],
        'headline-small': ['24px', { lineHeight: '32px', letterSpacing: '0px' }],
        'title-large': ['22px', { lineHeight: '28px', letterSpacing: '0px' }],
        'title-medium': ['16px', { lineHeight: '24px', letterSpacing: '0.15px' }],
        'title-small': ['14px', { lineHeight: '20px', letterSpacing: '0.1px' }],
        'body-large': ['16px', { lineHeight: '24px', letterSpacing: '0.5px' }],
        'body-medium': ['14px', { lineHeight: '20px', letterSpacing: '0.25px' }],
        'body-small': ['12px', { lineHeight: '16px', letterSpacing: '0.4px' }],
        'label-large': ['14px', { lineHeight: '20px', letterSpacing: '0.1px' }],
        'label-medium': ['12px', { lineHeight: '16px', letterSpacing: '0.5px' }],
        'label-small': ['11px', { lineHeight: '16px', letterSpacing: '0.5px' }],
      },
      borderRadius: {
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '28px',
      },
      boxShadow: {
        'elev-1': '0 1px 2px 0 rgba(0, 0, 0, 0.30), 0 1px 3px 1px rgba(0, 0, 0, 0.15)',
        'elev-2': '0 1px 2px 0 rgba(0, 0, 0, 0.30), 0 2px 6px 2px rgba(0, 0, 0, 0.15)',
        'elev-3': '0 1px 3px 0 rgba(0, 0, 0, 0.30), 0 4px 8px 3px rgba(0, 0, 0, 0.15)',
        'elev-4': '0 2px 3px 0 rgba(0, 0, 0, 0.30), 0 6px 10px 4px rgba(0, 0, 0, 0.15)',
        'elev-5': '0 4px 4px 0 rgba(0, 0, 0, 0.30), 0 8px 12px 6px rgba(0, 0, 0, 0.15)',
      },
      transitionTimingFunction: {
        standard: 'cubic-bezier(0.2, 0, 0, 1)',
        'standard-decelerate': 'cubic-bezier(0, 0, 0, 1)',
        'standard-accelerate': 'cubic-bezier(0.3, 0, 1, 1)',
        emphasized: 'cubic-bezier(0.2, 0, 0, 1)',
        'emphasized-decelerate': 'cubic-bezier(0.05, 0.7, 0.1, 1)',
        'emphasized-accelerate': 'cubic-bezier(0.3, 0, 0.8, 0.15)',
      },
      keyframes: {
        'fade-in': { from: { opacity: '0' }, to: { opacity: '1' } },
        'fade-out': { from: { opacity: '1' }, to: { opacity: '0' } },
        'dialog-in': {
          from: { opacity: '0', scale: '0.92' },
          to: { opacity: '1', scale: '1' },
        },
        'dialog-out': {
          from: { opacity: '1', scale: '1' },
          to: { opacity: '0', scale: '0.92' },
        },
        'sheet-in': {
          from: { transform: 'translateX(100%)' },
          to: { transform: 'translateX(0)' },
        },
        'sheet-out': {
          from: { transform: 'translateX(0)' },
          to: { transform: 'translateX(100%)' },
        },
        'snackbar-in': {
          from: { opacity: '0', transform: 'translateY(24px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'snackbar-out': {
          from: { opacity: '1', transform: 'translateY(0)' },
          to: { opacity: '0', transform: 'translateY(24px)' },
        },
        'menu-in': {
          from: { opacity: '0', scale: '0.95' },
          to: { opacity: '1', scale: '1' },
        },
        ripple: {
          from: { transform: 'scale(0)', opacity: '0.24' },
          to: { transform: 'scale(1)', opacity: '0' },
        },
        shimmer: {
          from: { transform: 'translateX(-100%)' },
          to: { transform: 'translateX(100%)' },
        },
      },
      animation: {
        'fade-in': 'fade-in 150ms cubic-bezier(0, 0, 0, 1)',
        'fade-out': 'fade-out 100ms cubic-bezier(0.3, 0, 1, 1)',
        'dialog-in': 'dialog-in 300ms cubic-bezier(0.05, 0.7, 0.1, 1)',
        'dialog-out': 'dialog-out 150ms cubic-bezier(0.3, 0, 0.8, 0.15)',
        'sheet-in': 'sheet-in 350ms cubic-bezier(0.05, 0.7, 0.1, 1)',
        'sheet-out': 'sheet-out 200ms cubic-bezier(0.3, 0, 0.8, 0.15)',
        'snackbar-in': 'snackbar-in 250ms cubic-bezier(0.05, 0.7, 0.1, 1)',
        'snackbar-out': 'snackbar-out 150ms cubic-bezier(0.3, 0, 0.8, 0.15)',
        'menu-in': 'menu-in 150ms cubic-bezier(0.05, 0.7, 0.1, 1)',
        ripple: 'ripple 500ms cubic-bezier(0.2, 0, 0, 1) forwards',
        shimmer: 'shimmer 1.6s linear infinite',
      },
    },
  },
  plugins: [],
}
